import { type NextPage } from "next";
import Head from "next/head";
import FormCreatePerson from "~/components/FormCreatePerson";

const AddExample: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create new person</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <FormCreatePerson />
    </>
  );
};

export default AddExample;
